spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:file:./db/moviestore
    username: sa
    password: password
    hikari:
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true

kinopoisk:
  x-api-key: ee97857e-9b91-4df5-b64f-576965097621
  url: https://kinopoiskapiunofficial.tech/api/v2.2/films

logging:
  level:
    root: info
    ru:
      home:
        moviestore: debug
